wandb_version: 1

load:
  desc: null
  value: null
savename:
  desc: null
  value: ./visuals/fishseparate
input:
  desc: null
  value: null
save_path:
  desc: null
  value: robot
batch_size:
  desc: null
  value: 24
prompt:
  desc: null
  value: robot and iron fish
start_vsd:
  desc: null
  value: 2000
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715733164.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.16.6
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
